site_name: EdgeX Global Pipelines Documentation
docs_dir: ./docs_src
site_dir: ./docs/html
site_description: 'Documentation for EdgeX Global Pipelines'
site_author: 'EdgeX DevOps Team'
site_url: 'https://edgexfoundry.github.io/edgex-global-pipelines/'
repo_url: 'https://github.com/edgexfoundry/edgex-global-pipelines'
repo_name: 'edgex/edgex-global-pipelines'
copyright: 'Copyright &copy; 2020 EdgeX Foundry'
google_analytics:
  - 'UA-82811140-6'
  - 'auto'
strict: true
theme:
  name: 'material'
  logo: 'assets/logo_edgex_white.png'
  favicon: 'assets/logo_edgex.png'
  features:
    - tabs
nav:
  - Introduction:
    - 'index.md'
  - Pipelines:
    - './libraries/edgeXBuildCApp.md'
    - './libraries/edgeXBuildDocker.md'
    - './libraries/edgeXBuildGoApp.md'
  - Tutorials:
    - './tutorials/index.md'
    - './tutorials/manual-bump.md'
    - './tutorials/pr-commit-for-testing.md'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/edgexfoundry'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/edgexfoundry'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/edgexfoundry'
extra_css:
  - assets\stylesheets\version-select.css
  - assets\stylesheets\branding.css