site_name: EdgeX Global Pipelines Documentation
docs_dir: ./docs_src
site_dir: ./docs/html
site_description: 'Documentation for EdgeX Global Pipelines'
site_author: 'EdgeX DevOps Team'
site_url: 'https://edgexfoundry.github.io/edgex-global-pipelines/'
repo_url: 'https://github.com/edgexfoundry/edgex-global-pipelines'
repo_name: 'edgex/edgex-global-pipelines'
copyright: 'Copyright &copy; 2022 EdgeX Foundry'
strict: false
theme:
  name: 'material'
  logo: 'assets/logo_edgex_white.png'
  favicon: 'assets/logo_edgex.png'
  analytics:
    gtag: 'G-38531ZZHBN'
  features:
    - tabs
nav:
  - Introduction:
    - 'index.md'
  - Pipelines:
    - './libraries/edgeXBuildCApp.md'
    - './libraries/edgeXBuildDocker.md'
    - './libraries/edgeXBuildGoApp.md'
    - './libraries/edgeXBuildGoParallel.md'
    - './libraries/edgeXBuildGoMod.md'
  - Miscellaneous Functions:
    - './libraries/edgex.md'
    - './libraries/edgeXCodecov.md'
    - './libraries/edgeXDocker.md'
    - './libraries/edgeXDockerLogin.md'
    - './libraries/edgeXEmail.md'
    - './libraries/edgeXEmailUtil.md'
    - './libraries/edgeXGHPagesPublish.md'
    - './libraries/edgeXInfraLFToolsSign.md'
    - './libraries/edgeXInfraPublish.md'
    - './libraries/edgeXNexusPublish.md'
    - './libraries/edgeXSetupEnvironment.md'
    - './libraries/edgeXSemver.md'
    - './libraries/edgeXSnyk.md'
    - './libraries/edgeXSwaggerPublish.md'
    - './libraries/edgeXUpdateNamedTag.md'
  - Release Functions:
    - './libraries/edgeXRelease.md'
    - './libraries/edgeXReleaseDockerImage.md'
    - './libraries/edgeXReleaseDocs.md'
    - './libraries/edgeXReleaseGitHubAssets.md'
    - './libraries/edgeXReleaseGitTag.md'
    - './libraries/edgeXLTS.md'
  - Deprecated Functions:
    - './libraries/edgeXClair.md'
    - './libraries/edgeXGeneric.md'
    - './libraries/edgeXInfraShipLogs.md'
    - './libraries/edgeXReleaseSnap.md'
    - './libraries/edgeXSnap.md'
  - Tutorials:
    - './tutorials/index.md'
    - './tutorials/docker-build-strategy.md'
    - './tutorials/manual-bump.md'
    - './tutorials/pr-commit-for-testing.md'
    - './tutorials/unit-testing-best-practices.md'
  - Release Info:
    - './releases/jakarta-release-stages.md'
    - './releases/jakarta-lts-initial.md'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/edgexfoundry'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/edgexfoundry'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/edgexfoundry'
extra_css:
  - assets\stylesheets\version-select.css
  - assets\stylesheets\branding.css